services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\StaticRolesBundle\Role\AbilitiesRoleHierarchy:
        decorates: 'security.role_hierarchy'
        arguments:
            $coreHierarchy: '@Becklyn\StaticRolesBundle\Role\AbilitiesRoleHierarchy.inner'

    becklyn.static_roles.role_collection:
        class: Becklyn\StaticRolesBundle\Role\RoleCollection


    becklyn.static_roles.form.type.static_role:
        class: Becklyn\StaticRolesBundle\Form\Type\StaticRoleType
        arguments:
            - "@becklyn.static_roles.role_collection"
        tags:
            - { name: form.type, alias: static_role }


    becklyn.static_roles.twig:
        class: Becklyn\StaticRolesBundle\Twig\StaticRolesTwigExtension
        arguments:
            - "@becklyn.static_roles.role_collection"
        tags:
            - { name: twig.extension }
