services:
    becklyn.static_roles.role_collection:
        class: Becklyn\StaticRolesBundle\Role\RoleCollection
        arguments:
            - ~ # set in the extension class

    becklyn.static_roles.role_hierarchy_voter:
        class: Becklyn\StaticRolesBundle\Voter\RoleHierarchyVoter
        arguments:
            - "@becklyn.static_roles.role_collection"
        tags:
            - { name: security.voter }


    becklyn.static_roles.form.type.static_role:
        class: Becklyn\StaticRolesBundle\Form\Type\StaticRoleType
        arguments:
            - "@becklyn.static_roles.role_collection"
        tags:
            - { name: form.type, alias: static_role }


    becklyn.static_roles.twig:
        class: Becklyn\StaticRolesBundle\Twig\StaticRolesTwigExtension
        arguments:
            - "@becklyn.static_roles.role_collection"
        tags:
            - { name: twig.extension }
