language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
    - composer self-update

install:
    - composer --prefer-source install

script: phpunit --configuration phpunit.xml --coverage-text
