services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\StaticRolesBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception,Resources,BecklynStaticRolesBundle.php}'

    Becklyn\StaticRolesBundle\Role\RoleCollection:
        decorates: 'security.role_hierarchy'
        arguments:
            $coreHierarchy: '%security.role_hierarchy.roles%'
